name: work_it
description: A new Flutter project.
publish_to: 'none'

version: 1.0.17+9

scripts:
  collection: "flutter pub run build_runner build"
  done: "rps build && rps release"
  build: "flutter build apk --split-per-abi"
  release: "gh release create v1.0.17 build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  collection: ^1.17.0
  date_utils: ^0.2.0
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  intl: any
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
